### ISSUE TITLE
Errors ending genview-makedb and required items for genview-visualize

### ISSUE THREAD

**Issue by drhoads** [EbmeyerSt/GEnView#6]
We are trying to get GEnView to run for us on our HPC cluster.  Installation complete, and I am testing by trying to examine a pathogenicity island gene in Staphylococcus.  The commands (without all the rsync stuff for running on the scratch space are:
$ genview-makedb -d ED98_GEnView -db ED98SaPI/ED98.peg.765.faa -p 32 -id 80 -scov 80 --uniprot_cutoff 60 --taxa 'staphylococcus' --assemblies --flanking_length 10000
$ genview-visualize -db ED98_GEnView/genview_database.db -o ED98_GEnView/765analyses 

I took that last one right off your wiki page but when the script got to that point it choked saying  -gene and -id are required.  Prior to that at the end of a 3 hour run for the genview-makedb there were a whole series of "tracebacks" such as:

Process Process-143:
Traceback (most recent call last):
  File "/share/apps/python/anaconda-3.9/envs/genview/lib/python3.10/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/share/apps/python/anaconda-3.9/envs/genview/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/share/apps/python/anaconda-3.9/envs/genview/lib/python3.10/site-packages/genview_scripts/genview_create_db.py", line 1167, in create_db
    arg_assemblies={line.split('\t')[0] for line in open(fa_file.replace(ending, '_annotated.csv'), 'r')}
FileNotFoundError: [Errno 2] No such file or directory: 'ED98_GEnView/all_assemblies_18._annotated.csv'

There were a bunch of these for a number of Process-XXX starting around Process-138 and occasionally interspersed with:
FileNotFoundError: [Errno 2] No such file or directory: 'ED98_GEnView/all_assemblies_13._annotated.csv'
FileNotFoundError: [Errno 2] No such file or directory: 'ED98_GEnView/all_assemblies_1._annotated.csv'
FileNotFoundError: [Errno 2] No such file or directory: 'ED98_GEnView/all_assemblies_4._annotated.csv'
FileNotFoundError: [Errno 2] No such file or directory: 'ED98_GEnView/all_assemblies_16._annotated.csv'
FileNotFoundError: [Errno 2] No such file or directory: 'ED98_GEnView/all_assemblies_3._annotated.csv'
FileNotFoundError: [Errno 2] No such file or directory: 'ED98_GEnView/all_assemblies_17._annotated.csv'
FileNotFoundError: [Errno 2] No such file or directory: 'ED98_GEnView/all_assemblies_11._annotated.csv'
FileNotFoundError: [Errno 2] No such file or directory: 'ED98_GEnView/all_assemblies_2._annotated.csv'

Any guidance or comments welcome.

**Comment by EbmeyerSt** [comment]
Hey, 

You are right, the command for genview-visualize on the wiki page was incomplete, I have now added -id and -gene. The complete command would then be "genview-visualize -db genview_database.db -o /path/to/genview_output_directory/per_80_analysis/ -id 80 -gene 'per'". The '-gene' parameter determines which gene loci are visualized - so if your genview database contains e.g the genes 'PER-1', 'PER-2' and 'PER-6' and you want to visualize the loci of all of these genes, you would specify the common denominator of these gene names 'per'. If you would only want to visualize PER-1 loci, you'd specify 'per-1'.

For traceback issue, it seems like the gene annotation files are missing, which means that diamond, the program GEnView uses for searching sequences, did not run properly. Could you post an example of the headers in your reference database specified under '-db'?

I will release a major update for GEnView at the end of next week or beginning of the week after. There I implement log files and some failsafes that should make GEnView more intuitive and self explanatory to run, plus you will be able to update previously created databases with new genomes.

**Comment by drhoads** [comment]
Pretty simple -db

>765
METGKSDVLDKIEKINKKDSALQEIIPKGYEIEHHQCGVALYQLIPSKKEGEPDKKVFIT
STIPQITERFEDIESNEVSFNMLFYDNKTPVNIAVSAEEISDSRQLLKLVNKKLDVTSST
STKLVDYINVSKRYNPPLNVKVATRLGHVKGYFIYPYQEVMKDSNVKLFSNDKGFQKLID
SFRSKGTLQGYSKKVFAQIKDLPMVMVMLYASLGSVLLREFGLQPFIVEISGSTSTGKTF
TLNLVSSVWGTSDLITTWSSTQNSIESMASFLNSFPMFKDDTRNTHPKFVTSATYNFSSG
ESKSRSNINLTLNAKKEWRNILISTGESSIANMADEKAGVSARVVTLQDPPYPDNFDFTT
LDKSFRENYGTLGLAFIKQYESKKDVYKKAFESYQRYFNQKGSNEIMQRLGRAFALLQVT
GEVLNDIDGFEHDHFKIIEQAYDSMVKNNKTIDKPKQLLEELLQYLDANRNNIAGDGYSS
VKNGDIKAIYKRDYLCILGETVKEKLTHELQTITGQWDKKGYLIKGEKDRLQKQVKHQTV
KYRGFAIRREVLEELGFDFSNSYNPNSDY

**Comment by drhoads** [comment]
Sorry, there is a > sign before 765

>765
METGKSDVLDKIEKINKKDSALQEIIPKGYEIEHHQCGVALYQLIPSKKEGEPDKKVFIT
STIPQITERFEDIESNEVSFNMLFYDNKTPVNIAVSAEEISDSRQLLKLVNKKLDVTSST
STKLVDYINVSKRYNPPLNVKVATRLGHVKGYFIYPYQEVMKDSNVKLFSNDKGFQKLID
SFRSKGTLQGYSKKVFAQIKDLPMVMVMLYASLGSVLLREFGLQPFIVEISGSTSTGKTF
TLNLVSSVWGTSDLITTWSSTQNSIESMASFLNSFPMFKDDTRNTHPKFVTSATYNFSSG
ESKSRSNINLTLNAKKEWRNILISTGESSIANMADEKAGVSARVVTLQDPPYPDNFDFTT
LDKSFRENYGTLGLAFIKQYESKKDVYKKAFESYQRYFNQKGSNEIMQRLGRAFALLQVT
GEVLNDIDGFEHDHFKIIEQAYDSMVKNNKTIDKPKQLLEELLQYLDANRNNIAGDGYSS
VKNGDIKAIYKRDYLCILGETVKEKLTHELQTITGQWDKKGYLIKGEKDRLQKQVKHQTV
KYRGFAIRREVLEELGFDFSNSYNPNSDY

**Comment by drhoads** [comment]
Supposedly made a database but there were some errors.  Then tried running genview-visualize on that database with this command:
genview-visualize -gene ED98SaPI/ED98.peg.765.faa -id 80 -db ED98_GEnView/genview_database.db -o ED98_GEnView/765analyses 
The .err file gives me this:
usage: genview-visualize [-h] -gene GENE -db DB -id ID [-nodes NODES]
                         [-taxa TAXA [TAXA ...]] [--force] [--compressed]
genview-visualize: error: unrecognized arguments: -o ED98_GEnView/765analyses

**Comment by drhoads** [comment]
The files in my target directory are all_assemblies_0 thru 19.fna, and .csv, as well as assembly_summary.txt, then the folders genomes and taxonomy

***@***.***

**Comment by drhoads** [comment]
Hmm, the google link is not to 'uniprotKBjan2019.fna, it is downloading uniprotKB_clustered_nohypo_merged_nospace_GN.fa.gz

***@***.***

**Comment by EbmeyerSt** [comment]
I see, in that case genview just renames the file. You can download the file, unzip it, rename it and put it into the target directory. Delete the other files genview created in the target directory and run it again, then everything should work as expected. Alternatively I can notify you once I have released the upcoming update, where this issue will be resolved.

**Comment by drhoads** [comment]
Clearly still having issues.  This is with the UniprotKB file and this is the end of the .err output:

FileNotFoundError: [Errno 2] No such file or directory: 'ED98_GEnView/all_assemblies_13._annotated.csv'
Process Process-150:
Traceback (most recent call last):
  File "/share/apps/python/anaconda-3.9/envs/genview/lib/python3.10/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/share/apps/python/anaconda-3.9/envs/genview/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/share/apps/python/anaconda-3.9/envs/genview/lib/python3.10/site-packages/genview_scripts/genview_create_db.py", line 1167, in create_db
    arg_assemblies={line.split('\t')[0] for line in open(fa_file.replace(ending, '_annotated.csv'), 'r')}
FileNotFoundError: [Errno 2] No such file or directory: 'ED98_GEnView/all_assemblies_5._annotated.csv'
usage: genview-visualize [-h] -gene GENE -db DB -id ID [-nodes NODES]
                         [-taxa TAXA [TAXA ...]] [--force] [--compressed]
genview-visualize: error: unrecognized arguments: -o ED98_GEnView/765analyses

***@***.***

**Comment by EbmeyerSt** [comment]
I think these issues might be due to incomplete files from previous analyses in the target directory or files being not downloaded correctly, but it's a bit difficult to say from a distance. Admittedly this seems to happen easily at the moment, so I would ask you to run it again after I release the update next week, where more internal checks are put in place to make sure files are complete and in the right places while running the software.

**Comment by drhoads** [comment]
Finally back to getting GEnView working.  We updated our HPC system to the new version.  I am testing everything interactively because the slurm script has been giving me issues.  genview-makedb, but I am stuck on the genview-visualize step.  I have captured the stdout.  I am just concerned that I don't know the correct value for -gene
The commands were:
genview-makedb -d genview -db genview/908_2501_2502.faa \
	-p 32 -id 80 -scov 80 --local fna --log \
	--uniprot_cutoff 60 --uniprot_db /scrfs/storag
[908_2501_2502.faa.txt](https://github.com/EbmeyerSt/GEnView/files/13926864/908_2501_2502.faa.txt)
e/drhoads/Data/uniprot/uniprotKB.dmnd 
genview-visualize -db genview/genview_database.db -gene POMKIKDF_2502 -id 80 

There are 73 assemblies in the fna folder, and the 908_2501_2502.faa file is attached (as a .txt) along with files.txt (files in genview after the runs) and genview.log which was stdout from the genview-visualize command.
[files.txt](https://github.com/EbmeyerSt/GEnView/files/13926857/files.txt)
[genview.log](https://github.com/EbmeyerSt/GEnView/files/13926858/genview.log)
